### ISSUE TITLE
Timestamp Bug

### ISSUE THREAD

**Issue by javaadpatel** [openlawteam/openlaw-client#140]
Hi, I am using the openlaw js client and it seems like the timestamp is incorrect I am assuming its supposed to be a unix timestamp? This is the response I get when calling executing `await apiClient.getTemplateVersions(openLawConfig.templateName, 20, 1);` 

![image](https://user-images.githubusercontent.com/22832462/67326843-5b84e600-f517-11e9-9176-d2ebfd724663.png)

In unix this would be:

![image](https://user-images.githubusercontent.com/22832462/67326914-6dff1f80-f517-11e9-8a89-43a598bcf4e0.png)

In the documentation as well, this timestamp is similar:
![image](https://user-images.githubusercontent.com/22832462/67326768-45772580-f517-11e9-9d6b-5dbfecf434f7.png)

**Comment by jtrein** [comment]
Hi @javaadpatel I've run these inputs through `Date()` and they appear OK.

```
new Date(1571759717000)
Tue Oct 22 2019 16:55:17 GMT+0100 (British Summer Time)
new Date(1537509029000)
Fri Sep 21 2018 06:50:29 GMT+0100 (British Summer Time)
```

**Comment by javaadpatel** [comment]
@jtrein, it does work when using `Date` but I think that's just a caveat of how javascript's Date function works, because I think it works using milliseconds. The actual input `1571759717000` is not a valid unix timestamp.

var date = new Date(UNIX_Timestamp * 1000)

so the actual unix_timestamp would be `1571759717`. If this is how its intended to be used then that's fine, i just thought it was a unix timestamp.

**Comment by jtrein** [comment]
Hi @javaadpatel you're correct. We could be more clear about this in our documentation, perhaps. Since it is a JS library targeting a JS client, operating in milliseconds is the valid way (as you've alluded to). 🙂
