### ISSUE TITLE
Remove getUserDetails method from APIClient

### ISSUE THREAD

**Issue by jtrein** [openlawteam/openlaw-client#65]
Ref: https://github.com/openlawteam/openlaw-elements/issues/53

In short, it's dead code, now.

**Comment by jtrein** [comment]
This is a breaking change for user apps, as noted by @jdville03

**Comment by mroth** [comment]
> This is a breaking change for user apps, as noted by @jdville03

I'm guessing we should at least bump minor version instead of patch in next release to respect semantic versioning conventions? (It think normally a reverse-incompatible API change is considered a major release, but prior to 1.0.0 the guarantees are relaxed and it can be a minor?)

**Comment by jdville03** [comment]
We'll go with a minor version bump for this change.

**Comment by jdville03** [comment]
Fixed in #66
