### ISSUE TITLE
getAccessToken call not working, returning 404 error. 

### ISSUE THREAD

**Issue by mcchan1** [openlawteam/openlaw-client#72]
## Problem/Enhancement
getAccessToken call not working, returning 404 error.  Original 404 error was on the app.openlaw.io instance.  I get the same error for this call on the 'develop' and 'app-rc' instance.  Tried with multiple templates, but I'm testing it out on  "OpenLaw API Tutorial Sale Agreement" template on the 'develop' instance. 

## Wireframes
![image](https://user-images.githubusercontent.com/6320310/58579341-d4a63880-8218-11e9-9705-2f7be7f5e474.png)

## Acceptance Criteria

- [ ] getAccessToken call does not return 404 error

## Special QA Instructions

[Optional: Anything special QA should know about this? ]

## Related Tasks

[Optional: Link to other tasks that are related.]

**Comment by jtrein** [comment]
Hi, @mcchan1 I've tested this in another app, but authenticating to the `develop` instance. I used the following code:

```
// get access token(s) using contract id
apiClient.getAccessToken([contractIdString])
      .then(({ data }) => console.log(data));

// RESPONSE

{
  "[email]@consensys.net": "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx"
}
```

I haven't received any 404 so far. If you take a look at your Request Headers in a Chrome console do you see an `OPENLAW_JWT`?

**Comment by jtrein** [comment]
In our Scala code it does issue a `NotFound` response if it cannot find the contract, or the `creatorId !== request.currentUserId`

**Comment by mcchan1** [comment]
@jtrein hmm.. I do get an OPENLAW_JWT, but I'm still receiving the 404, even when using the same creatorId as I used to make the template.  I'm testing on this repo https://github.com/openlawteam/openlaw-api-tutorial  on lines 110 - 115.

**Comment by jtrein** [comment]
@jdville03 Do you have any ideas here? I'm not sure we're using this call inside our main app. Is there a reference of this working elsewhere?

**Comment by jdville03** [comment]
Hey guys sorry just coming around to this one. @mcchan1 is this still an issue for you? If so, I can take a closer look tomorrow.

**Comment by outkaj** [comment]
@mcchan1 is this still an issue for you?

**Comment by mcchan1** [comment]
@outkaj yes, still same issue.

**Comment by jdville03** [comment]
@mcchan1 do you want to try to pair so we can see what's going on? Something to keep in mind is that it can only be called by the contract creator (the user hitting "Send" when done from the app UI). That could be different than the creator of the template. Are you possibly conflating the two in your code?

**Comment by mcchan1** [comment]
@jdville03 Thanks. I'll double check if I am. If thats not the issue, then lets pair up.

**Comment by mcchan1** [comment]
@jdville03  I just tried with a fresh template, but same result.  Can we pair on Monday or early next week?

**Comment by jdville03** [comment]
Update - we got the `getAccessToken` call to work after fixing the `uploadContract` call. The issue was some of the params required for that `uploadContract` call were not in the correct format.
